### PR TITLE
Add file contexts in /usr for /bin, /usr/sbin and /usr/lib

### PR DESCRIPTION
**Pull request by fishilico**
Some policy modules define file contexts in /bin, /sbin and /lib without defining similar file contexts in the same directory under /usr.

Add these missing file contexts when there are outside ifdef blocks.

### CODE REVIEW

**Comment by pebenito** [comment]
Is this due to a distrubution replacing /bin with a symlink to /usr/bin (or the reverse)? If so a path substitution is more suitable.

**Comment by fishilico** [comment]
Yes, on Arch Linux and soon Debian (according to https://wiki.debian.org/UsrMerge), /bin is a symlink to /usr/bin. Without any path substitution, programs like /usr/bin/ping or /usr/bin/ip get labelled as bin_t instead of their specific ..._exec_t file contexts:

    # matchpathcon /usr/bin/ping /usr/bin/ip
    /usr/bin/ping   system_u:object_r:bin_t
    /usr/bin/ip     system_u:object_r:bin_t

As far as I understand, adding "/bin /usr/bin" in the path substitutions makes solving the file contexts for files in /bin/ using the /usr/bin/ prefix instead, which does not fix the problem. Doing the substitution the other way round worsens the problem as there are less file contexts defined in /bin than in /usr/bin.
How path substitutions can be used so that both file context patterns in /usr/bin and /bin can be searched for a given path?

**Comment by cgzones** [comment]
what about something reckless like a new boolean?
https://github.com/TresysTechnology/refpolicy/compare/master...cgzones:usr_merge?expand=1

**Comment by pebenito** [comment]
I'd prefer not to have code that alters policy files in a way that is not easy to undo (from the perspective of someone using a .tar of the source tree, not a git checkout) if possible.

**Comment by fishilico** [comment]
With ``$(SED) -i 's/^\/sbin\//\/usr\/sbin\//' $<.fc``, the resulting file may contain several definitions for the same pattern. On my system, using ``semodule -i`` on a module with duplicate file context definitions produce this error:
```
/var/lib/selinux/final/refpolicy-patched/contexts/files/file_contexts: Multiple same specifications for /....
/var/lib/selinux/final/refpolicy-patched/contexts/files/file_contexts: Invalid argument
libsemanage.semanage_validate_and_compile_fcontexts: setfiles returned error code 1.
semodule:  Failed!
```
Therefore I also prefer not to have code which automatically patches files at build time.

@pebenito : as you do not seem to like the patch I sent in this PR, how would you solve the issue that systems with symlinks `/bin->/usr/bin` and `/sbin->/usr/sbin` currently have?

**Comment by pebenito** [comment]
I've reconsidered and will take the patches, but they need to be rebased.

**Comment by fishilico** [comment]
Thanks. I have rebased and fixed the conflicts with the recent `/run` file context change. In files which had conflicts I also moved the `/run/...` contexts before the `/usr` ones to make the file more consistent in regards to the alphabetical order.

**Pull request merged**
