### PR TITLE
update Makefile

### PR DESCRIPTION
**Pull request by cgzones**
- immediate set several variables
- some stricter tooling options:
  - m4 -E -E
  - python -t -t
  - CC -Wextra -Werror -O2
- only run sedoctool once for `booleans.conf` and once for `modules.conf`

### CODE REVIEW

**Comment by pebenito** [comment]
I'm ok with these changes except for the last one, which seems that the change does the reverse of what you say above.

Here's the log of master: https://travis-ci.org/TresysTechnology/refpolicy/jobs/180570105#L1349 
and here's this PR: https://travis-ci.org/TresysTechnology/refpolicy/jobs/180176471#L1357

**Comment by cgzones** [comment]
wow, it seems to have something to do with MONOLITHIC=y/n
see the log from your reference master build: (142.2, you showed 142.1)
https://travis-ci.org/TresysTechnology/refpolicy/jobs/180570106#L1339

**Comment by cgzones** [comment]
maybe a timing issue in combination with `make`? cause Rules.modular contains much more targets than Rules.monolithic?

The script `python -E support/sedoctool.py -b policy/booleans.conf -m policy/modules.conf -x doc/policy.xml` has the same runtime for me with both configurations but i get different make debug output:
make conf MONOLITHIC=y --debug=v

```
[...]
   Finished prerequisites of target file 'policy/modules.conf'.
  Must remake target 'policy/modules.conf'.
Updating policy/modules.conf and policy/booleans.conf
python -E support/sedoctool.py -b policy/booleans.conf -m policy/modules.conf -x doc/policy.xml
  Successfully remade target file 'policy/modules.conf'.
  Considering target file 'policy/booleans.conf'.
    Pruning file 'doc/policy.xml'.
   Finished prerequisites of target file 'policy/booleans.conf'.
   Prerequisite 'doc/policy.xml' is older than target 'policy/booleans.conf'.
  No need to remake target 'policy/booleans.conf'.
  Pruning file 'policy/modules/kernel/corenetwork.te'.
  Pruning file 'policy/modules/kernel/corenetwork.if'.
 Finished prerequisites of target file 'conf'.
Must remake target 'conf'.
Successfully remade target file 'conf'.
```

make conf MONOLITHIC=n --debug=v

```
[...]
  Finished prerequisites of target file 'policy/modules.conf'.
 Must remake target 'policy/modules.conf'.
Updating policy/modules.conf and policy/booleans.conf
python -E support/sedoctool.py -b policy/booleans.conf -m policy/modules.conf -x doc/policy.xml
 Successfully remade target file 'policy/modules.conf'.
 Considering target file 'policy/booleans.conf'.
  File 'policy/booleans.conf' does not exist.
   Pruning file 'doc/policy.xml'.
  Finished prerequisites of target file 'policy/booleans.conf'.
 Must remake target 'policy/booleans.conf'.
Updating policy/modules.conf and policy/booleans.conf
python -E support/sedoctool.py -b policy/booleans.conf -m policy/modules.conf -x doc/policy.xml
 Successfully remade target file 'policy/booleans.conf'.
 Finished prerequisites of target file 'conf'.
Must remake target 'conf'.
Successfully remade target file 'conf'.
```

**Comment by pebenito** [comment]
I'd prefer to drop that change unless there is something wrong with the contents of the output files.

**Comment by cgzones** [comment]
what about me recent change towards using an intermediate target?
i do not like that under any build settings the sedoctool command is running twice, cause this may cause under some rare circumstances some troubles with multi-threading etc.

**Pull request merged**
