### PR TITLE
fix syslogd audits

### PR DESCRIPTION
**Pull request by cgzones**

### CODE REVIEW

**Comment by pebenito** [comment]
Which syslog is generating these denials?

**Comment by doverride** [comment]
On 12/04/2016 07:10 PM, Chris PeBenito wrote:
> Which syslog is generating these denials?
> 

That is probably systemd-journald running in the syslogd_t domain?


-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8  02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift

**Comment by pebenito** [comment]
If thats the case, I'd like the audit socket access in an init_systemd block.

**Comment by cgzones** [comment]
Yes, these denials were caused by systemd-journald

**Pull request merged**
