### PR TITLE
corecommands: fix usr merge

### PR DESCRIPTION
**Pull request by cgzones**

### CODE REVIEW

**Comment by cgzones** [comment]
not quite, i added some rules to `corecmd_search_bin`, which are needed, when /bin is a symlink to /usr/bin

**Comment by pebenito** [comment]
Ok, but if you are going to deprecate interfaces, you have to fix all uses of it too (see travis-ci output)

**Comment by cgzones** [comment]
updated and adjusted with https://github.com/TresysTechnology/refpolicy-contrib/pull/50

**Comment by pebenito** [comment]
Generally it's ok to include searches for parent directories. No need for a new usr type.

**Pull request merged**
