### PR TITLE
userdomain: strengthen user terminals access

### PR DESCRIPTION
**Pull request by cgzones**
prohibit open by using inherited perms, introduced by Russell Coker

### CODE REVIEW

**Comment by cgzones** [comment]
For 100% backward compatibility: yes a new interface would be needed.
But properly most of the callers do not need the open permission, and converting and testing all of them would be tedious.
One exception I found is screen/tmux (screen_domain).

**Comment by pebenito** [comment]
It should be easy to fix the usage. Use sed :)

**Comment by pebenito** [comment]
Nonetheless the compatibility needs to be preserved.

**Comment by cgzones** [comment]
is the new approach better?

**Comment by pebenito** [comment]
I think the interface changes are fine, though I think the TODOs aren't necessary.

**Comment by pebenito** [comment]
Please drop the TODOs and I'll merge.

**Comment by cgzones** [comment]
rebased, btw. can you document the usage of analysis annotation like `<infoflow type="both" weight="10"/>` or `<rolecap/>`

**Pull request merged**
